# Specify a non-default branch for pull requests

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dependabot-2"
    # Labels on pull requests for security and version updates
    labels:
      - "LABEL npm dependencies"
